uvdesk_community_installation_wizard:
    path:     /
    controller: Wizard\Controller\Wizard::load

uvdesk_community_installation_wizard_check_requirements:
    path:     /wizard/xhr/check-requirements
    controller: Wizard\Controller\WizardXHR::evaluateSystemRequirements
    methods: [POST]

uvdesk_community_installation_wizard_verify_database_credentials:
    path:     /wizard/xhr/verify-database-credentials
    controller: Wizard\Controller\WizardXHR::verifyDatabaseCredentials
    methods: [POST]

uvdesk_community_installation_wizard_store_super_user_credentials:
    path:     /wizard/xhr/intermediary/super-user
    controller: Wizard\Controller\WizardXHR::prepareSuperUserDetailsXHR
    methods: [POST]

uvdesk_community_installation_wizard_store_website_configuration:
    path:     /wizard/xhr/website-configure
    controller: Wizard\Controller\WizardXHR::websiteConfigurationXHR

uvdesk_community_installation_wizard_update_configurations_xhr:
    path:     /wizard/xhr/load/configurations
    controller: Wizard\Controller\WizardXHR::updateConfigurationsXHR
    methods: [POST]

uvdesk_community_installation_wizard_migrate_database_schema_xhr:
    path:     /wizard/xhr/load/migrations
    controller: Wizard\Controller\WizardXHR::migrateDatabaseSchemaXHR
    methods: [POST]

uvdesk_community_installation_wizard_populate_database_entities_xhr:
    path:     /wizard/xhr/load/entities
    controller: Wizard\Controller\WizardXHR::populateDatabaseEntitiesXHR
    methods: [POST]

uvdesk_community_installation_wizard_create_default_super_user_xhr:
    path:     /wizard/xhr/load/super-user
    controller: Wizard\Controller\WizardXHR::createDefaultSuperUserXHR
    methods: [POST]

uvdesk_community_installation_wizard_update_website_configuration:
    path:     /wizard/xhr/load/website-configure
    controller: Wizard\Controller\WizardXHR::updateWebsiteConfigurationXHR
    methods: [POST]
