services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    _instanceof:
        UVDesk\CommunityPackages\UVDesk\ECommerce\Utils\ECommercePlatformInterface:
            lazy: true
            tags: [UVDesk\CommunityPackages\UVDesk\ECommerce\Utils\ECommercePlatformInterface]
    
    UVDesk\CommunityPackages\UVDesk\ECommerce\:
        resource: '../../*'
        # exclude: '../../{Scripts}'
    
    UVDesk\CommunityPackages\UVDesk\ECommerce\Utils\ECommerceConfiguration:
        lazy: true
        configurator: ['@UVDesk\CommunityPackages\UVDesk\ECommerce\Configs\ComponentConfigurator', 'prepareECommerceConfiguration']
