uvdesk_community_installation_wizard:
    path:     /
    controller: Webkul\UVDesk\Wizard\Controller\Wizard::load

# uvdesk_community_installation_wizard_check_requirements:
#     path:     /wizard/xhr/check-requirements
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::evaluateSystemRequirements
#     methods: [POST]

# uvdesk_community_installation_wizard_verify_database_credentials:
#     path:     /wizard/xhr/verify-database-credentials
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::verifyDatabaseCredentials
#     methods: [POST]

# uvdesk_community_installation_wizard_store_super_user_credentials:
#     path:     /wizard/xhr/intermediary/super-user
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::prepareSuperUserDetailsXHR
#     methods: [POST]

# uvdesk_community_installation_wizard_store_website_configuration:
#     path:     /wizard/xhr/website-configure
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::websiteConfigurationXHR

# uvdesk_community_installation_wizard_update_configurations_xhr:
#     path:     /wizard/xhr/load/configurations
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::updateConfigurationsXHR
#     methods: [POST]

# uvdesk_community_installation_wizard_migrate_database_schema_xhr:
#     path:     /wizard/xhr/load/migrations
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::migrateDatabaseSchemaXHR
#     methods: [POST]

# uvdesk_community_installation_wizard_populate_database_entities_xhr:
#     path:     /wizard/xhr/load/entities
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::populateDatabaseEntitiesXHR
#     methods: [POST]

# uvdesk_community_installation_wizard_create_default_super_user_xhr:
#     path:     /wizard/xhr/load/super-user
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::createDefaultSuperUserXHR
#     methods: [POST]

# uvdesk_community_installation_wizard_update_website_configuration:
#     path:     /wizard/xhr/load/website-configure
#     controller: Webkul\UVDesk\Wizard\Controller\InstallationWizardXHR::updateWebsiteConfigurationXHR
#     methods: [POST]
