services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Webkul\UVDesk\Wizard\:
        resource: '../../*'

    Webkul\UVDesk\Wizard\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    
    Webkul\UVDesk\Wizard\Routes\Wizard:
        tags:
            - { name: uvdesk.router, env: dev }
