services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wizard\:
        resource: '../../*'
        exclude: '../../{Console,Routes.php}'

    Wizard\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
    
    Wizard\Routes:
        tags: ['uvdesk.router']
