services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Webkul\UVDesk\Wizard\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Webkul\UVDesk\Wizard\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
